from Matrix import Matrix

A = [[1.0,2.0,3.0],[2.0,3.0,1.0],[4.0,5.0,1.0]]
print("Testing Matrix Module for Matrix A = \n",A)
M = Matrix(A)

print("\nTesting LU Factorization")
L,U = M.LUFactorization()
print("L:")
print(L)
print("U:")
print(U)

print("\nTesting LUP Factorization")
L,U,P = M.LUPFactorization()
print("L:")
print(L)
print("U:")
print(U)
print("P:")
print(P)

print("\nTesting LUP Factorization in Parallel")
L,U,P = M.LUPFactorization(True)
print("L:")
print(L)
print("U:")
print(U)
print("P:")
print(P)

print("\nTesting QR Factorization")
Q,R = M.QRFactorization()
print("Q:")
print(Q)
print("R:")
print(R)

print("\nTesting QRCP Factorization")
Q,R,Cp = M.QRCPFactorization()
print("Q:")
print(Q)
print("R:")
print(R)
print("Cp:")
print(Cp)

print("\nTesting QRCP Factorization in Parallel")
Q,R,Cp = M.QRCPFactorization(True)
print("Q:")
print(Q)
print("R:")
print(R)
print("Cp:")
print(Cp)
